on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: run pep8 linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the directory
        uses: actions/checkout@v2

      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1.2.0
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .

      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1
